language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO=1.8.18
  - DJANGO=1.9.13
  - DJANGO=1.10.7
  - DJANGO=1.11.1

script:
  - pip install Django==$DJANGO
  - python setup.py test
